// PLEASE DO NOT EDIT THIS FILE, THIS IS GENERATED BY NATIVEBLOCKS

package integration

type ColumnBlockProperty struct {
	Key          string `json:"key"`
	ValueMobile  string `json:"valueMobile"`
	ValueTablet  string `json:"valueTablet"`
	ValueDesktop string `json:"valueDesktop"`
	Type         string `json:"type"`
}

type ColumnBlockData struct {
	Key   string `json:"key"`
	Value string `json:"value"`
	Type  string `json:"type"`
}

type ColumnBlockAction struct {
	Event    string        `json:"event"`
	Triggers []interface{} `json:"triggers"`
}

type ColumnBlockSlot struct {
	Slot string `json:"slot"`
}

type ColumnBlockEvent struct {
	Event string `json:"event"`
}

type ColumnBlock struct {
	keyType            string
	integrationVersion int
	properties         []ColumnBlockProperty
	data               []ColumnBlockData
	events             []ColumnBlockEvent
	actions            []ColumnBlockAction
	blocks             []interface{}
	slots              []ColumnBlockSlot
	visibilityKey      string
	slot               string
	key                string
}

func NewColumnBlock(_key string, _visibilityKey string, _slot string) ColumnBlock {
	c := ColumnBlock{}
	c.keyType = "COLUMN"
	c.key = _key
	c.visibilityKey = _visibilityKey
	c.slot = _slot
	c.actions = make([]ColumnBlockAction, 0)
	c.blocks = make([]interface{}, 0)
	initialProperties := []ColumnBlockProperty{
		{Key: "verticalArrangement", ValueMobile: "top", ValueTablet: "top", ValueDesktop: "top", Type: "STRING"},
		{Key: "horizontalAlignment", ValueMobile: "top", ValueTablet: "top", ValueDesktop: "top", Type: "STRING"},
		{Key: "width", ValueMobile: "wrap", ValueTablet: "wrap", ValueDesktop: "wrap", Type: "STRING"},
		{Key: "height", ValueMobile: "wrap", ValueTablet: "wrap", ValueDesktop: "wrap", Type: "STRING"},
		{Key: "paddingStart", ValueMobile: "8.0", ValueTablet: "8.0", ValueDesktop: "8.0", Type: "DOUBLE"},
		{Key: "paddingTop", ValueMobile: "8.0", ValueTablet: "8.0", ValueDesktop: "8.0", Type: "DOUBLE"},
		{Key: "paddingEnd", ValueMobile: "8.0", ValueTablet: "8.0", ValueDesktop: "8.0", Type: "DOUBLE"},
		{Key: "paddingBottom", ValueMobile: "8.0", ValueTablet: "8.0", ValueDesktop: "8.0", Type: "DOUBLE"},
		{Key: "background", ValueMobile: "#ffffffff", ValueTablet: "#ffffffff", ValueDesktop: "#ffffffff", Type: "STRING"},
		{Key: "direction", ValueMobile: "LTR", ValueTablet: "LTR", ValueDesktop: "LTR", Type: "STRING"},
		{Key: "radiusTopStart", ValueMobile: "4.0", ValueTablet: "4.0", ValueDesktop: "4.0", Type: "DOUBLE"},
		{Key: "radiusTopEnd", ValueMobile: "4.0", ValueTablet: "4.0", ValueDesktop: "4.0", Type: "DOUBLE"},
		{Key: "radiusBottomStart", ValueMobile: "4.0", ValueTablet: "4.0", ValueDesktop: "4.0", Type: "DOUBLE"},
		{Key: "radiusBottomEnd", ValueMobile: "4.0", ValueTablet: "4.0", ValueDesktop: "4.0", Type: "DOUBLE"},
	}
	c.properties = initialProperties

	initialData := []ColumnBlockData{}
	c.data = initialData

	initialSlots := []ColumnBlockSlot{
		{Slot: "content"},
	}
	c.slots = initialSlots

	initialEvents := []ColumnBlockEvent{
		{Event: "onClick"},
	}
	c.events = initialEvents

	return c
}

func (c *ColumnBlock) isValidEvent(eventName string) bool {
	for _, e := range c.events {
		if e.Event == eventName {
			return true
		}
	}
	return false
}

func (c *ColumnBlock) isValidBlock(block interface{}) bool {
	if block == nil {
		return false
	}
	m, ok := block.(map[string]interface{})
	if !ok {
		return false
	}
	_, hasKey := m["key"]
	_, hasKeyType := m["keyType"]
	return hasKey && hasKeyType
}

func (c *ColumnBlock) AddAction(event string, triggers []interface{}) *ColumnBlock {
	if !c.isValidEvent(event) {
		var eventNames string
		for _, ev := range c.events {
			eventNames += ev.Event
		}
		panic("Invalid event: " + event + ". Must be one of: " + eventNames)
	}
	action := ColumnBlockAction{Event: event, Triggers: triggers}
	c.actions = append(c.actions, action)
	return c
}

func (c *ColumnBlock) AddBlock(block interface{}) *ColumnBlock {
	if !c.isValidBlock(block) {
		panic("Invalid block: Block must be a map with at least key and keyType")
	}
	c.blocks = append(c.blocks, block)
	return c
}

func (c *ColumnBlock) ModifyProperty(key, valueMobile, valueTablet, valueDesktop string) *ColumnBlock {
	for i, p := range c.properties {
		if p.Key == key {
			c.properties[i].ValueMobile = valueMobile
			c.properties[i].ValueTablet = valueTablet
			c.properties[i].ValueDesktop = valueDesktop
			break
		}
	}
	return c
}

func (c *ColumnBlock) Build() map[string]interface{} {
	result := map[string]interface{}{
		"keyType":            c.keyType,
		"integrationVersion": c.integrationVersion,
		"properties":         c.properties,
		"data":               c.data,
		"key":                c.key,
		"visibilityKey":      c.visibilityKey,
		"slot":               c.slot,
		"slots":              c.slots,
		"actions":            c.actions,
		"blocks":             c.blocks,
	}
	return result
}
