// PLEASE DO NOT EDIT THIS FILE, THIS IS GENERATED BY NATIVEBLOCKS

package integration

type ImageBlockProperty struct {
	Key          string `json:"key"`
	ValueMobile  string `json:"valueMobile"`
	ValueTablet  string `json:"valueTablet"`
	ValueDesktop string `json:"valueDesktop"`
	Type         string `json:"type"`
}

type ImageBlockData struct {
	Key   string `json:"key"`
	Value string `json:"value"`
	Type  string `json:"type"`
}

type ImageBlockAction struct {
	Event    string        `json:"event"`
	Triggers []interface{} `json:"triggers"`
}

type ImageBlockSlot struct {
	Slot string `json:"slot"`
}

type ImageBlockEvent struct {
	Event string `json:"event"`
}

type ImageBlock struct {
	keyType            string
	integrationVersion int
	properties         []ImageBlockProperty
	data               []ImageBlockData
	events             []ImageBlockEvent
	actions            []ImageBlockAction
	blocks             []interface{}
	slots              []ImageBlockSlot
	visibilityKey      string
	slot               string
	key                string
}

func NewImageBlock(_key string, _visibilityKey string, _slot string) ImageBlock {
	c := ImageBlock{}
	c.keyType = "IMAGE"
	c.key = _key
	c.visibilityKey = _visibilityKey
	c.slot = _slot
	c.actions = make([]ImageBlockAction, 0)
	c.blocks = make([]interface{}, 0)
	initialProperties := []ImageBlockProperty{
		{Key: "width", ValueMobile: "wrap", ValueTablet: "wrap", ValueDesktop: "wrap", Type: "STRING"},
		{Key: "height", ValueMobile: "wrap", ValueTablet: "wrap", ValueDesktop: "wrap", Type: "STRING"},
		{Key: "radiusTopStart", ValueMobile: "4.0", ValueTablet: "4.0", ValueDesktop: "4.0", Type: "DOUBLE"},
		{Key: "radiusTopEnd", ValueMobile: "4.0", ValueTablet: "4.0", ValueDesktop: "4.0", Type: "DOUBLE"},
		{Key: "radiusBottomStart", ValueMobile: "4.0", ValueTablet: "4.0", ValueDesktop: "4.0", Type: "DOUBLE"},
		{Key: "radiusBottomEnd", ValueMobile: "4.0", ValueTablet: "4.0", ValueDesktop: "4.0", Type: "DOUBLE"},
		{Key: "scaleType", ValueMobile: "none", ValueTablet: "none", ValueDesktop: "none", Type: "STRING"},
	}
	c.properties = initialProperties

	initialData := []ImageBlockData{
		{Key: "imageUrl", Value: "", Type: "STRING"},
		{Key: "contentDescription", Value: "", Type: "STRING"},
	}
	c.data = initialData

	initialSlots := []ImageBlockSlot{}
	c.slots = initialSlots

	initialEvents := []ImageBlockEvent{}
	c.events = initialEvents

	return c
}

func (c *ImageBlock) isValidEvent(eventName string) bool {
	for _, e := range c.events {
		if e.Event == eventName {
			return true
		}
	}
	return false
}

func (c *ImageBlock) isValidBlock(block interface{}) bool {
	if block == nil {
		return false
	}
	m, ok := block.(map[string]interface{})
	if !ok {
		return false
	}
	_, hasKey := m["key"]
	_, hasKeyType := m["keyType"]
	return hasKey && hasKeyType
}

func (c *ImageBlock) ModifyProperty(key, valueMobile, valueTablet, valueDesktop string) *ImageBlock {
	for i, p := range c.properties {
		if p.Key == key {
			c.properties[i].ValueMobile = valueMobile
			c.properties[i].ValueTablet = valueTablet
			c.properties[i].ValueDesktop = valueDesktop
			break
		}
	}
	return c
}

func (c *ImageBlock) AssignData(key, value string) *ImageBlock {
	for i, d := range c.data {
		if d.Key == key {
			c.data[i].Value = value
			break
		}
	}
	return c
}

func (c *ImageBlock) Build() map[string]interface{} {
	result := map[string]interface{}{
		"keyType":            c.keyType,
		"integrationVersion": c.integrationVersion,
		"properties":         c.properties,
		"data":               c.data,
		"key":                c.key,
		"visibilityKey":      c.visibilityKey,
		"slot":               c.slot,
		"slots":              c.slots,
		"actions":            c.actions,
		"blocks":             c.blocks,
	}
	return result
}
