// PLEASE DO NOT EDIT THIS FILE, THIS IS GENERATED BY NATIVEBLOCKS

package integration

type RootBlockProperty struct {
	Key          string `json:"key"`
	ValueMobile  string `json:"valueMobile"`
	ValueTablet  string `json:"valueTablet"`
	ValueDesktop string `json:"valueDesktop"`
	Type         string `json:"type"`
}

type RootBlockData struct {
	Key   string `json:"key"`
	Value string `json:"value"`
	Type  string `json:"type"`
}

type RootBlockAction struct {
	Event    string        `json:"event"`
	Triggers []interface{} `json:"triggers"`
}

type RootBlockSlot struct {
	Slot string `json:"slot"`
}

type RootBlockEvent struct {
	Event string `json:"event"`
}

type RootBlock struct {
	keyType            string
	integrationVersion int
	properties         []RootBlockProperty
	data               []RootBlockData
	events             []RootBlockEvent
	actions            []RootBlockAction
	blocks             []interface{}
	slots              []RootBlockSlot
	visibilityKey      string
	slot               string
	key                string
}

func NewRootBlock(_key string, _visibilityKey string, _slot string) RootBlock {
	c := RootBlock{}
	c.keyType = "ROOT"
	c.key = _key
	c.visibilityKey = _visibilityKey
	c.slot = _slot
	c.actions = make([]RootBlockAction, 0)
	c.blocks = make([]interface{}, 0)
	initialProperties := []RootBlockProperty{
		{Key: "direction", ValueMobile: "LTR", ValueTablet: "LTR", ValueDesktop: "LTR", Type: "STRING"},
		{Key: "paddingTop", ValueMobile: "8", ValueTablet: "8", ValueDesktop: "8", Type: "INT"},
		{Key: "paddingStart", ValueMobile: "8", ValueTablet: "8", ValueDesktop: "8", Type: "INT"},
		{Key: "paddingEnd", ValueMobile: "8", ValueTablet: "8", ValueDesktop: "8", Type: "INT"},
		{Key: "paddingBottom", ValueMobile: "8", ValueTablet: "8", ValueDesktop: "8", Type: "INT"},
		{Key: "background", ValueMobile: "#ffffff", ValueTablet: "#ffffff", ValueDesktop: "#ffffff", Type: "STRING"},
		{Key: "horizontalAlignment", ValueMobile: "top", ValueTablet: "top", ValueDesktop: "top", Type: "STRING"},
		{Key: "verticalArrangement", ValueMobile: "top", ValueTablet: "top", ValueDesktop: "top", Type: "STRING"},
	}
	c.properties = initialProperties

	initialData := []RootBlockData{}
	c.data = initialData

	initialSlots := []RootBlockSlot{
		{Slot: "content"},
	}
	c.slots = initialSlots

	initialEvents := []RootBlockEvent{
		{Event: "onAppear"},
		{Event: "onDisappear"},
	}
	c.events = initialEvents

	return c
}

func (c *RootBlock) isValidEvent(eventName string) bool {
	for _, e := range c.events {
		if e.Event == eventName {
			return true
		}
	}
	return false
}

func (c *RootBlock) isValidBlock(block interface{}) bool {
	if block == nil {
		return false
	}
	m, ok := block.(map[string]interface{})
	if !ok {
		return false
	}
	_, hasKey := m["key"]
	_, hasKeyType := m["keyType"]
	return hasKey && hasKeyType
}

func (c *RootBlock) AddAction(event string, triggers []interface{}) *RootBlock {
	if !c.isValidEvent(event) {
		var eventNames string
		for _, ev := range c.events {
			eventNames += ev.Event
		}
		panic("Invalid event: " + event + ". Must be one of: " + eventNames)
	}
	action := RootBlockAction{Event: event, Triggers: triggers}
	c.actions = append(c.actions, action)
	return c
}

func (c *RootBlock) AddBlock(block interface{}) *RootBlock {
	if !c.isValidBlock(block) {
		panic("Invalid block: Block must be a map with at least key and keyType")
	}
	c.blocks = append(c.blocks, block)
	return c
}

func (c *RootBlock) ModifyProperty(key, valueMobile, valueTablet, valueDesktop string) *RootBlock {
	for i, p := range c.properties {
		if p.Key == key {
			c.properties[i].ValueMobile = valueMobile
			c.properties[i].ValueTablet = valueTablet
			c.properties[i].ValueDesktop = valueDesktop
			break
		}
	}
	return c
}

func (c *RootBlock) Build() map[string]interface{} {
	result := map[string]interface{}{
		"keyType":            c.keyType,
		"integrationVersion": c.integrationVersion,
		"properties":         c.properties,
		"data":               c.data,
		"key":                c.key,
		"visibilityKey":      c.visibilityKey,
		"slot":               c.slot,
		"slots":              c.slots,
		"actions":            c.actions,
		"blocks":             c.blocks,
	}
	return result
}
