<?php

// PLEASE DO NOT EDIT THIS FILE, THIS IS GENERATED BY NATIVEBLOCKS

namespace App\Integrations; 

class ImageBlock
{
    private string $keyType;
    private int $integrationVersion;
    private array $properties = [];
    private array $data = [];
    private array $events = [];
    private array $actions = [];
    private array $blocks = [];
    private array $slots = [];
    private string $visibilityKey;
    private string $slot;
    private string $key;

    public function __construct(array $config = [])
    {
        $this->keyType = 'IMAGE';
        $this->integrationVersion = 3;
        $this->key = $config['key'] ?? '';
        $this->visibilityKey = $config['visibilityKey'] ?? '';
        $this->slot = $config['slot'] ?? '';
        $this->actions = [];
        $this->blocks = [];
        $initialProperties = [
            ['key' => 'width', 'valueMobile' => 'wrap', 'valueTablet' => 'wrap', 'valueDesktop' => 'wrap', 'type' => 'STRING'],
            ['key' => 'height', 'valueMobile' => 'wrap', 'valueTablet' => 'wrap', 'valueDesktop' => 'wrap', 'type' => 'STRING'],
            ['key' => 'radiusTopStart', 'valueMobile' => '4.0', 'valueTablet' => '4.0', 'valueDesktop' => '4.0', 'type' => 'DOUBLE'],
            ['key' => 'radiusTopEnd', 'valueMobile' => '4.0', 'valueTablet' => '4.0', 'valueDesktop' => '4.0', 'type' => 'DOUBLE'],
            ['key' => 'radiusBottomStart', 'valueMobile' => '4.0', 'valueTablet' => '4.0', 'valueDesktop' => '4.0', 'type' => 'DOUBLE'],
            ['key' => 'radiusBottomEnd', 'valueMobile' => '4.0', 'valueTablet' => '4.0', 'valueDesktop' => '4.0', 'type' => 'DOUBLE'],
            ['key' => 'scaleType', 'valueMobile' => 'none', 'valueTablet' => 'none', 'valueDesktop' => 'none', 'type' => 'STRING'],
        ];
        $this->properties = $initialProperties;

        $initialData = [
            ['key' => 'imageUrl', 'value' => null, 'type' => 'STRING'],
            ['key' => 'contentDescription', 'value' => null, 'type' => 'STRING'],
        ];
        $this->data = $initialData;

        $initialSlots = [
        ];
        $this->slots = $initialSlots;

        $initialEvents = [
        ];
        $this->events = $initialEvents;
    }

    private function isValidEvent(string $eventName): bool
    {
        foreach ($this->events as $event) {
            if ($event['event'] === $eventName) {
                return true;
            }
        }
        return false;
    }

    private function isValidBlock(array $block): bool
    {
        return isset($block['key']) && isset($block['keyType']);
    }

    public function modifyProperty(string $key, string $valueMobile, string $valueTablet, string $valueDesktop): self
    {
        foreach ($this->properties as &$property) {
            if ($property['key'] === $key) {
                $property['valueMobile'] = $valueMobile;
                $property['valueTablet'] = $valueTablet;
                $property['valueDesktop'] = $valueDesktop;
                break;
            }
        }
        return $this;
    }

    public function assignData(string $key, $value): self
    {
        foreach ($this->data as &$data) {
            if ($data['key'] === $key) {
                $data['value'] = $value;
                break;
            }
        }
        return $this;
    }

    public function build(): array
    {
        return [
            'keyType' => $this->keyType,
            'key' => $this->key,
            'visibilityKey' => $this->visibilityKey,
            'slot' => $this->slot,
            'slots' => $this->slots,
            'actions' => $this->actions,
            'blocks' => $this->blocks,
            'data' => $this->data,
            'properties' => $this->properties,
            'integrationVersion' => $this->integrationVersion,
        ];
    }
}
