<?php

// PLEASE DO NOT EDIT THIS FILE, THIS IS GENERATED BY NATIVEBLOCKS

namespace App\Integrations; 

class TextFieldBlock
{
    private string $keyType;
    private int $integrationVersion;
    private array $properties = [];
    private array $data = [];
    private array $events = [];
    private array $actions = [];
    private array $blocks = [];
    private array $slots = [];
    private string $visibilityKey;
    private string $slot;
    private string $key;

    public function __construct(array $config = [])
    {
        $this->keyType = 'TEXT_FIELD';
        $this->integrationVersion = 5;
        $this->key = $config['key'] ?? '';
        $this->visibilityKey = $config['visibilityKey'] ?? '';
        $this->slot = $config['slot'] ?? '';
        $this->actions = [];
        $this->blocks = [];
        $initialProperties = [
            ['key' => 'maxLines', 'valueMobile' => '100', 'valueTablet' => '100', 'valueDesktop' => '100', 'type' => 'INT'],
            ['key' => 'width', 'valueMobile' => 'wrap', 'valueTablet' => 'wrap', 'valueDesktop' => 'wrap', 'type' => 'STRING'],
            ['key' => 'height', 'valueMobile' => 'wrap', 'valueTablet' => 'wrap', 'valueDesktop' => 'wrap', 'type' => 'STRING'],
            ['key' => 'contentColor', 'valueMobile' => '#FFFFFFFF', 'valueTablet' => '#FFFFFFFF', 'valueDesktop' => '#FFFFFFFF', 'type' => 'STRING'],
            ['key' => 'disabledContentColor', 'valueMobile' => '#FFFFFFB2', 'valueTablet' => '#FFFFFFB2', 'valueDesktop' => '#FFFFFFB2', 'type' => 'STRING'],
            ['key' => 'backgroundColor', 'valueMobile' => '#FF212121', 'valueTablet' => '#FF212121', 'valueDesktop' => '#FF212121', 'type' => 'STRING'],
            ['key' => 'disableBackgroundColor', 'valueMobile' => '#212121B2', 'valueTablet' => '#212121B2', 'valueDesktop' => '#212121B2', 'type' => 'STRING'],
            ['key' => 'borderColor', 'valueMobile' => '#FF212121', 'valueTablet' => '#FF212121', 'valueDesktop' => '#FF212121', 'type' => 'STRING'],
            ['key' => 'disableBorderColor', 'valueMobile' => '#212121B2', 'valueTablet' => '#212121B2', 'valueDesktop' => '#212121B2', 'type' => 'STRING'],
            ['key' => 'borderFocusColor', 'valueMobile' => '#FF212121', 'valueTablet' => '#FF212121', 'valueDesktop' => '#FF212121', 'type' => 'STRING'],
            ['key' => 'shadow', 'valueMobile' => '1', 'valueTablet' => '1', 'valueDesktop' => '1', 'type' => 'INT'],
            ['key' => 'radiusTopStart', 'valueMobile' => '4.0', 'valueTablet' => '4.0', 'valueDesktop' => '4.0', 'type' => 'DOUBLE'],
            ['key' => 'radiusTopEnd', 'valueMobile' => '4.0', 'valueTablet' => '4.0', 'valueDesktop' => '4.0', 'type' => 'DOUBLE'],
            ['key' => 'radiusBottomStart', 'valueMobile' => '4.0', 'valueTablet' => '4.0', 'valueDesktop' => '4.0', 'type' => 'DOUBLE'],
            ['key' => 'radiusBottomEnd', 'valueMobile' => '4.0', 'valueTablet' => '4.0', 'valueDesktop' => '4.0', 'type' => 'DOUBLE'],
            ['key' => 'paddingStart', 'valueMobile' => '4.0', 'valueTablet' => '4.0', 'valueDesktop' => '4.0', 'type' => 'DOUBLE'],
            ['key' => 'paddingTop', 'valueMobile' => '4.0', 'valueTablet' => '4.0', 'valueDesktop' => '4.0', 'type' => 'DOUBLE'],
            ['key' => 'paddingEnd', 'valueMobile' => '4.0', 'valueTablet' => '4.0', 'valueDesktop' => '4.0', 'type' => 'DOUBLE'],
            ['key' => 'paddingBottom', 'valueMobile' => '4.0', 'valueTablet' => '4.0', 'valueDesktop' => '4.0', 'type' => 'DOUBLE'],
            ['key' => 'fontSize', 'valueMobile' => '14.0', 'valueTablet' => '14.0', 'valueDesktop' => '14.0', 'type' => 'DOUBLE'],
            ['key' => 'fontFamily', 'valueMobile' => 'default', 'valueTablet' => 'default', 'valueDesktop' => 'default', 'type' => 'STRING'],
            ['key' => 'textAlign', 'valueMobile' => 'start', 'valueTablet' => 'start', 'valueDesktop' => 'start', 'type' => 'STRING'],
            ['key' => 'fontWeight', 'valueMobile' => 'normal', 'valueTablet' => 'normal', 'valueDesktop' => 'normal', 'type' => 'STRING'],
            ['key' => 'letterSpacing', 'valueMobile' => '1.25', 'valueTablet' => '1.25', 'valueDesktop' => '1.25', 'type' => 'DOUBLE'],
            ['key' => 'direction', 'valueMobile' => 'LTR', 'valueTablet' => 'LTR', 'valueDesktop' => 'LTR', 'type' => 'STRING'],
            ['key' => 'keyboardType', 'valueMobile' => 'normal', 'valueTablet' => 'normal', 'valueDesktop' => 'normal', 'type' => 'STRING'],
        ];
        $this->properties = $initialProperties;

        $initialData = [
            ['key' => 'text', 'value' => null, 'type' => 'STRING'],
            ['key' => 'placeholder', 'value' => null, 'type' => 'STRING'],
            ['key' => 'label', 'value' => null, 'type' => 'STRING'],
            ['key' => 'enable', 'value' => null, 'type' => 'BOOLEAN'],
            ['key' => 'readOnly', 'value' => null, 'type' => 'BOOLEAN'],
        ];
        $this->data = $initialData;

        $initialSlots = [
            ['slot' => 'onLeadingIcon'],
            ['slot' => 'onTrailingIcon'],
        ];
        $this->slots = $initialSlots;

        $initialEvents = [
            ['event' => 'onTextChange'],
        ];
        $this->events = $initialEvents;
    }

    private function isValidEvent(string $eventName): bool
    {
        foreach ($this->events as $event) {
            if ($event['event'] === $eventName) {
                return true;
            }
        }
        return false;
    }

    private function isValidBlock(array $block): bool
    {
        return isset($block['key']) && isset($block['keyType']);
    }

    public function addAction(string $event, array $triggers): self
    {
        if (!$this->isValidEvent($event)) {
            throw new \Exception(sprintf('Invalid event: %s', $event));
        }
        array_push($this->actions, ['event' => $event, 'triggers' => $triggers]);
        return $this;
    }

    public function addBlock(array $block): self
    {
        if (!$this->isValidBlock($block)) {
            throw new \Exception('Invalid block: Block must be an array with at least key and keyType');
        }
        array_push($this->blocks, $block);
        return $this;
    }

    public function modifyProperty(string $key, string $valueMobile, string $valueTablet, string $valueDesktop): self
    {
        foreach ($this->properties as &$property) {
            if ($property['key'] === $key) {
                $property['valueMobile'] = $valueMobile;
                $property['valueTablet'] = $valueTablet;
                $property['valueDesktop'] = $valueDesktop;
                break;
            }
        }
        return $this;
    }

    public function assignData(string $key, $value): self
    {
        foreach ($this->data as &$data) {
            if ($data['key'] === $key) {
                $data['value'] = $value;
                break;
            }
        }
        return $this;
    }

    public function build(): array
    {
        return [
            'keyType' => $this->keyType,
            'key' => $this->key,
            'visibilityKey' => $this->visibilityKey,
            'slot' => $this->slot,
            'slots' => $this->slots,
            'actions' => $this->actions,
            'blocks' => $this->blocks,
            'data' => $this->data,
            'properties' => $this->properties,
            'integrationVersion' => $this->integrationVersion,
        ];
    }
}
