// PLEASE DO NOT EDIT THIS FILE, THIS IS GENERATED BY NATIVEBLOCKS

interface IProperty {
  key: string;
  valueMobile: string;
  valueTablet: string;
  valueDesktop: string;
  type: string;
}

interface IData {
  key: string;
  value: any;
  type: string;
}

interface IAction {
  event: string;
  triggers: any[];
}

interface ISlot {
  slot: string;
}

interface IEvent {
  event: string;
}

export class SpacerBlock {
  private readonly keyType: string;
  private readonly integrationVersion: number;
  private properties: IProperty[];
  private data: IData[];
  private readonly events: IEvent[];
  private actions: IAction[];
  private blocks: any[];
  private readonly slots: ISlot[];
  private readonly visibilityKey: string;
  private readonly slot: string;
  private readonly key: string;

  constructor(config: {
    key: string;
    visibilityKey: string;
    slot: string;
  } = {} as any) {
    this.keyType = "SPACER";
    this.key = config.key;
    this.visibilityKey = config.visibilityKey;
    this.slot = config.slot;
    this.actions = [];
    this.blocks = [];
    this.slots = [];
    this.integrationVersion = 2;
    this.properties = [];
    this.data = [];
    this.events = [];
    const initialProperties: IProperty[] = [
      { key: "width", valueMobile: "wrap", valueTablet: "wrap", valueDesktop: "wrap", type: "STRING" },
      { key: "height", valueMobile: "wrap", valueTablet: "wrap", valueDesktop: "wrap", type: "STRING" },
    ];
    this.properties.push(...initialProperties);
    const initialData: IData[] = [
    ];
    this.data.push(...initialData);
    const initialSlots: ISlot[] = [
    ];
    this.slots.push(...initialSlots);
    const initialEvents: IEvent[] = [
    ];
    this.events.push(...initialEvents);
  }

  private isValidEvent(eventName: string): boolean {
    return this.events.some((e) => e.event === eventName);
  }

  private isValidBlock(block: any): boolean {
    return block &&
           typeof block === "object" &&
           block.key &&
           block.keyType;
  }

  public modifyProperty(key: string, valueMobile: string, valueTablet: string, valueDesktop: string): this {
    const propIndex = this.properties.findIndex((p) => p.key === key);
    if (propIndex !== -1) {
      this.properties[propIndex] = { ...this.properties[propIndex], valueMobile, valueTablet, valueDesktop };
    }
    return this;
  }

  public build(): any {
    return {
      keyType: this.keyType,
      key: this.key,
      visibilityKey: this.visibilityKey,
      slot: this.slot,
      slots: this.slots,
      actions: this.actions,
      blocks: this.blocks,
      data: this.data,
      properties: this.properties,
      integrationVersion: this.integrationVersion,
    };
  }
}
