// PLEASE DO NOT EDIT THIS FILE, THIS IS GENERATED BY NATIVEBLOCKS 
class rootBlock {
  keyType;
  integrationVersion;
  properties;
  data;
  events;
  actions;
  blocks;
  slots;
  visibilityKey;
  slot;
  key;

  constructor(config = {}) {
    this.keyType = "ROOT";
    this.key = config.key;
    this.visibilityKey = config.visibilityKey;
    this.slot = config.slot;
    this.actions = [];
    this.blocks = [];
    this.slots = [];
    this.integrationVersion = 4;
    this.properties = [];
    this.data = [];
    this.events = [];
    const initialProperties = [
      { key: "direction", valueMobile: "LTR", valueTablet: "LTR", valueDesktop: "LTR", type: "STRING" },
      { key: "paddingTop", valueMobile: "8", valueTablet: "8", valueDesktop: "8", type: "INT" },
      { key: "paddingStart", valueMobile: "8", valueTablet: "8", valueDesktop: "8", type: "INT" },
      { key: "paddingEnd", valueMobile: "8", valueTablet: "8", valueDesktop: "8", type: "INT" },
      { key: "paddingBottom", valueMobile: "8", valueTablet: "8", valueDesktop: "8", type: "INT" },
      { key: "background", valueMobile: "#ffffff", valueTablet: "#ffffff", valueDesktop: "#ffffff", type: "STRING" },
      { key: "horizontalAlignment", valueMobile: "top", valueTablet: "top", valueDesktop: "top", type: "STRING" },
      { key: "verticalArrangement", valueMobile: "top", valueTablet: "top", valueDesktop: "top", type: "STRING" },
    ];
    this.properties.push(...initialProperties);
    const initialData = [
    ];
    this.data.push(...initialData);
    const initialSlots = [
      { slot: "content" },
    ];
    this.slots.push(...initialSlots);
    const initialEvents = [
      { event: "onAppear" },
      { event: "onDisappear" },
    ];
    this.events.push(...initialEvents);
  }

  isValidEvent(eventName) {
    return this.events.some(e => e.event === eventName);
  }

  isValidBlock(block) {
    return block && 
           typeof block === "object" && 
           block.key && 
           block.keyType;
  }

  addAction(event, triggers) {
    if (!this.isValidEvent(event)) {
      throw new Error(`Invalid event: ${event}. Must be one of: ${this.events.map(e => e.event).join(", ")}`);
    }
    const action = { event, triggers: triggers };
    this.actions.push(action);
    return this;
  }

  getAction(event) {
    return this.actions.find(a => a.event === event);
  }

  addBlock(block) {
    if (!this.isValidBlock(block)) {
      throw new Error("Invalid block: Block must be an object with at least key and keyType");
    }
    this.blocks.push(block);
    return this;
  }

  getBlock(key) {
    return this.blocks.find(b => b.key === key);
  }

  getBlocks() {
    return [...this.blocks];
  }

  modifyProperty(key, valueMobile, valueTablet, valueDesktop) {
    const propIndex = this.properties.findIndex(p => p.key === key);
    if (propIndex !== -1) {
      this.properties[propIndex] = { ...this.properties[propIndex], valueMobile, valueTablet, valueDesktop };
    }
    return this;
  }

  assignData(key, value) {
    const dataIndex = this.data.findIndex(d => d.key === key);
    if (dataIndex !== -1) {
      this.data[dataIndex] = { ...this.data[dataIndex], value };
    }
    return this;
  }

  build() {
    return {
      keyType: this.keyType,
      key: this.key,
      visibilityKey: this.visibilityKey,
      slot: this.slot,
      slots: this.slots,
      actions: this.actions,
      blocks: this.blocks,
      data: this.data,
      properties: this.properties,
      integrationVersion: this.integrationVersion,
    };
  }
}

module.exports = rootBlock;
