// PLEASE DO NOT EDIT THIS FILE, THIS IS GENERATED BY NATIVEBLOCKS 
class textFieldBlock {
  keyType;
  integrationVersion;
  properties;
  data;
  events;
  actions;
  blocks;
  slots;
  visibilityKey;
  slot;
  key;

  constructor(config = {}) {
    this.keyType = "TEXT_FIELD";
    this.key = config.key;
    this.visibilityKey = config.visibilityKey;
    this.slot = config.slot;
    this.actions = [];
    this.blocks = [];
    this.slots = [];
    this.integrationVersion = 5;
    this.properties = [];
    this.data = [];
    this.events = [];
    const initialProperties = [
      { key: "maxLines", valueMobile: "100", valueTablet: "100", valueDesktop: "100", type: "INT" },
      { key: "width", valueMobile: "wrap", valueTablet: "wrap", valueDesktop: "wrap", type: "STRING" },
      { key: "height", valueMobile: "wrap", valueTablet: "wrap", valueDesktop: "wrap", type: "STRING" },
      { key: "contentColor", valueMobile: "#FFFFFFFF", valueTablet: "#FFFFFFFF", valueDesktop: "#FFFFFFFF", type: "STRING" },
      { key: "disabledContentColor", valueMobile: "#FFFFFFB2", valueTablet: "#FFFFFFB2", valueDesktop: "#FFFFFFB2", type: "STRING" },
      { key: "backgroundColor", valueMobile: "#FF212121", valueTablet: "#FF212121", valueDesktop: "#FF212121", type: "STRING" },
      { key: "disableBackgroundColor", valueMobile: "#212121B2", valueTablet: "#212121B2", valueDesktop: "#212121B2", type: "STRING" },
      { key: "borderColor", valueMobile: "#FF212121", valueTablet: "#FF212121", valueDesktop: "#FF212121", type: "STRING" },
      { key: "disableBorderColor", valueMobile: "#212121B2", valueTablet: "#212121B2", valueDesktop: "#212121B2", type: "STRING" },
      { key: "borderFocusColor", valueMobile: "#FF212121", valueTablet: "#FF212121", valueDesktop: "#FF212121", type: "STRING" },
      { key: "shadow", valueMobile: "1", valueTablet: "1", valueDesktop: "1", type: "INT" },
      { key: "radiusTopStart", valueMobile: "4.0", valueTablet: "4.0", valueDesktop: "4.0", type: "DOUBLE" },
      { key: "radiusTopEnd", valueMobile: "4.0", valueTablet: "4.0", valueDesktop: "4.0", type: "DOUBLE" },
      { key: "radiusBottomStart", valueMobile: "4.0", valueTablet: "4.0", valueDesktop: "4.0", type: "DOUBLE" },
      { key: "radiusBottomEnd", valueMobile: "4.0", valueTablet: "4.0", valueDesktop: "4.0", type: "DOUBLE" },
      { key: "paddingStart", valueMobile: "4.0", valueTablet: "4.0", valueDesktop: "4.0", type: "DOUBLE" },
      { key: "paddingTop", valueMobile: "4.0", valueTablet: "4.0", valueDesktop: "4.0", type: "DOUBLE" },
      { key: "paddingEnd", valueMobile: "4.0", valueTablet: "4.0", valueDesktop: "4.0", type: "DOUBLE" },
      { key: "paddingBottom", valueMobile: "4.0", valueTablet: "4.0", valueDesktop: "4.0", type: "DOUBLE" },
      { key: "fontSize", valueMobile: "14.0", valueTablet: "14.0", valueDesktop: "14.0", type: "DOUBLE" },
      { key: "fontFamily", valueMobile: "default", valueTablet: "default", valueDesktop: "default", type: "STRING" },
      { key: "textAlign", valueMobile: "start", valueTablet: "start", valueDesktop: "start", type: "STRING" },
      { key: "fontWeight", valueMobile: "normal", valueTablet: "normal", valueDesktop: "normal", type: "STRING" },
      { key: "letterSpacing", valueMobile: "1.25", valueTablet: "1.25", valueDesktop: "1.25", type: "DOUBLE" },
      { key: "direction", valueMobile: "LTR", valueTablet: "LTR", valueDesktop: "LTR", type: "STRING" },
      { key: "keyboardType", valueMobile: "normal", valueTablet: "normal", valueDesktop: "normal", type: "STRING" },
    ];
    this.properties.push(...initialProperties);
    const initialData = [
      { key: "text", value: null, type: "STRING" },
      { key: "placeholder", value: null, type: "STRING" },
      { key: "label", value: null, type: "STRING" },
      { key: "enable", value: null, type: "BOOLEAN" },
      { key: "readOnly", value: null, type: "BOOLEAN" },
    ];
    this.data.push(...initialData);
    const initialSlots = [
      { slot: "onLeadingIcon" },
      { slot: "onTrailingIcon" },
    ];
    this.slots.push(...initialSlots);
    const initialEvents = [
      { event: "onTextChange" },
    ];
    this.events.push(...initialEvents);
  }

  isValidEvent(eventName) {
    return this.events.some(e => e.event === eventName);
  }

  isValidBlock(block) {
    return block && 
           typeof block === "object" && 
           block.key && 
           block.keyType;
  }

  addAction(event, triggers) {
    if (!this.isValidEvent(event)) {
      throw new Error(`Invalid event: ${event}. Must be one of: ${this.events.map(e => e.event).join(", ")}`);
    }
    const action = { event, triggers: triggers };
    this.actions.push(action);
    return this;
  }

  getAction(event) {
    return this.actions.find(a => a.event === event);
  }

  addBlock(block) {
    if (!this.isValidBlock(block)) {
      throw new Error("Invalid block: Block must be an object with at least key and keyType");
    }
    this.blocks.push(block);
    return this;
  }

  getBlock(key) {
    return this.blocks.find(b => b.key === key);
  }

  getBlocks() {
    return [...this.blocks];
  }

  modifyProperty(key, valueMobile, valueTablet, valueDesktop) {
    const propIndex = this.properties.findIndex(p => p.key === key);
    if (propIndex !== -1) {
      this.properties[propIndex] = { ...this.properties[propIndex], valueMobile, valueTablet, valueDesktop };
    }
    return this;
  }

  assignData(key, value) {
    const dataIndex = this.data.findIndex(d => d.key === key);
    if (dataIndex !== -1) {
      this.data[dataIndex] = { ...this.data[dataIndex], value };
    }
    return this;
  }

  build() {
    return {
      keyType: this.keyType,
      key: this.key,
      visibilityKey: this.visibilityKey,
      slot: this.slot,
      slots: this.slots,
      actions: this.actions,
      blocks: this.blocks,
      data: this.data,
      properties: this.properties,
      integrationVersion: this.integrationVersion,
    };
  }
}

module.exports = textFieldBlock;
